repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: Ruff lint
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: ruff-format-check
        name: Ruff format check
        entry: uv run ruff format --check --exclude tests .
        language: system
        pass_filenames: false
        types_or: [python, pyi]
